# NOTE: You need to pass in a variable group containing the expo username & password
parameters:
   env: ""
   app: ""
   variable_groups: []
   # (Required) Comma delimited list of all build commands to execute
   build_commands: ""
   depends_on: ""
   condition: ""
stages:
   - stage: deploy_expo_${{ parameters.app }}_${{ parameters.env }}
     displayName: "Deploy Multi - ${{ parameters.env }} - ${{ parameters.app }}"
     dependsOn: "${{ parameters.depends_on }}"
     condition: "${{ parameters.condition }}"
     variables: 
        - ${{ each group in parameters.variable_groups }}:
            - group: ${{ group }}
     jobs:
        - deployment: deploy_${{ parameters.app }}_${{ parameters.env }}
          displayName: "Deploy Multi ${{ parameters.app }} - ${{ parameters.env }}"
          environment: "${{ parameters.env }}"
          pool:
             vmImage: "ubuntu-latest"
          strategy:
             runOnce:
                deploy:
                   steps:
                      - template: "../../utility/azure-devops/task-cancel-previous-releases.yml"
                      - template: "../../utility/expo/task-deploy-expo-multi-app.yml"
                        parameters:
                           build_commands: ${{ parameters.build_commands }}